version: '3'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace  # Mount the entire project directory
    ports:
      - "8000:8000"
      - "3000:3000"
